### ISSUE TITLE
Yes, your several codes comes many problems ...

### ISSUE THREAD

**Issue by mycoin** [sindresorhus/is-obj#5]
![image](https://user-images.githubusercontent.com/1845440/78385922-41474c00-760f-11ea-8a1c-2d3d4a11b127.png)

es5 please....

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
