### ISSUE TITLE
On Node 13, I kept receive "is-obj require() of ES modules is not supported"

### ISSUE THREAD

**Issue by pablodegrande** [sindresorhus/is-obj#8]
Another module used require to include is-obj, and that broke compilation. I had to remove type: module from is-obj's package.json and migrate the code to:

module.exports = function(value) {
	const type = typeof value;
	return value !== null && (type === 'object' || type === 'function');
}

are you planning to apply this change? it would be nice, as under node 13 otherwise is-obj compiles as an ES module, and breaks compiling.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
